### PR TITLE
public groups

### PR DESCRIPTION
**Pull request by matthewdias**
- properly hides posts in private groups
- allows posting, commenting, and liking by non-members (that are not banned)

### CODE REVIEW

**Comment by JoshFabian** [comment]
What happens if I'm a non-member that has never been banned and I'm behaving in a way that should get me banned?

**Comment by matthewdias** [comment]
Ah, thanks for the catch. We need to have a way to ban non-members.

**Comment by NuckChorris** [comment]
Do we really want the ability for drive-by Posts?

**Comment by NuckChorris** [comment]
Also I think GroupBan can be applied to nonmembers with some minor frontend tweaks?

**Comment by matthewdias** [comment]
Yeah looking at it now I think it can. Regarding drive-bys, I think with the changes being made to feeds, groups will become more important for discussion that doesn't align with Interests. I really don't want to have to join a group to make one post, and then have all the posts for that group in my following feed, for example. Basically the way I see groups after this change is: A group is a topic-focused feed that anyone can interact with, provided they are not banned, and if I am active enough in a group that I want to see all its posts, I can join the group and have them appear in my following feed. Happy to revert if it's a dumb idea.

**Comment by JoshFabian** [comment]
I will say that's it's a little bit strange for a non-group member to participate in a group, and it might hurt some of the intimacy of what a group offers. That said, I'm happy to give this a try - if it becomes problematic, we can always revert!

**Comment by JoshFabian** [comment]
I will say that's it's a little bit strange for a non-group member to participate in a group, and it might hurt some of the intimacy of what a group offers. That said, I'm happy to give this a try - if it becomes problematic, we can always revert!

**Review by NuckChorris — APPROVED** [review]

**Review by NuckChorris — APPROVED** [review]

**Pull request merged**
