### PR TITLE
rails admin fixes

### PR DESCRIPTION
**Pull request by matthewdias**
[bug](https://kitsu.io/feedback/bugs/p/rails-admin-config-bugs)

- [x] make list view not terrible
- [x] episodes
- [x] mappings
- [x] streaming links
- [x] media relationships

### CODE REVIEW

**Comment by matthewdias** [comment]
Trying to get this to work. https://github.com/sferik/rails_admin/pull/2461

**Comment by NuckChorris** [comment]
Looks like @synthtech beat you to episodes

**Comment by matthewdias** [comment]
nah, what i want to fix in this pr is the media field on episodes (and the others). right now it's just a dropdown, so it tries to load everything and fails. working on changing it to a search field like the non-polymorphic associations have. see https://kitsu.io/feedback/bugs/p/rails-admin-config-bugs

**Comment by NuckChorris** [comment]
Oh, awesome!  Yeah, looks like they did some work on that upstream and then never merged it :(

**Comment by NuckChorris** [comment]
Does it really need all that copy+pasted JS? 🤔 Can we reduce what's copied to the bare minimum?

**Comment by matthewdias** [comment]
ill see what i can strip out.

**Pull request merged**
