### PR TITLE
Move User.website into ProfileLinkSite Seeds

### PR DESCRIPTION
**Pull request by toyhammered**
Going to push migration up next

### CODE REVIEW

**Comment by NuckChorris** [comment]
Looks like you need to remove the `website` attribute on the `UserResource` and change the `UsersController` spec to account for not being able to set a `website` attribute

**Comment by trmcnvn** [comment]
Could we get these conflicts resolved? /cc @toyhammered

**Comment by toyhammered** [comment]
will do!

**Comment by toyhammered** [comment]
@vevix nuck is going to check it over should be merged tonight.

**Review by NuckChorris — APPROVED** [review]

**Review by trmcnvn — APPROVED** [review]

**Pull request merged**
