### PR TITLE
GraphQL - downcase all slug lookups

### PR DESCRIPTION
**Pull request by toyhammered**
# What

When looking up using a slug, this will always downcase it before hand.

# Why

# Checklist

- [ ] All files pass Rubocop
- [ ] Any complex logic is commented
- [ ] Any new systems have thorough documentation
- [ ] Any user-facing changes are behind a feature flag (or: explain why they can't be)

- [ ] All the tests pass
- [ ] Tests have been added to cover the new code

### CODE REVIEW

**Comment by wopian** [comment]
I don't think this will work. [Slugs are case-**in**sensitive](https://github.com/hummingbird-me/kitsu-server/blob/a816c093e6c3df2151198e23f94bdde2d19ad9df/app/models/user.rb#L188) but the query performed in GraphQL _is_ case-sensitive. I believe the Postgres query will need to be told to use something along the lines of `WHERE slug ILIKE :slug` or the [citext module](http://www.postgresql.org/docs/current/interactive/citext.html), unless there's another way in `graphql-ruby`.

### Before PR

| Actual Slug | findProfileBySlug | Found Profile? 
| :-: | :-: | :-:
| `wopian` (l) | `wopian` (l) | ✔️ 
| `wopian` (l) | `Wopian` (u) | ❌ 
| `Wopian` (u) | `wopian` (l) | ❌ 
| `Wopian` (u) | `Wopian` (u) | ✔️ 

### With PR

| Actual Slug | findProfileBySlug  | Found Profile? 
| :-: | :-: | :-:
| `wopian` (l) | `wopian` (l) | ✔️ 
| `wopian` (l) | `Wopian` (u) | ✔️ 
| `Wopian` (u) | `wopian` (l) | ❌ 
| `Wopian` (u) | `Wopian` (u) | ❌ 

### JSON:API

| Actual Slug | filter[slug] | Found Profile? 
| :-: | :-: | :-:
| `wopian` (l) | `wopian` (l) | ✔️ 
| `wopian` (l) | `Wopian` (u) | ✔️ 
| `Wopian` (u) | `wopian` (l) | ✔️ 
| `Wopian` (u) | `Wopian` (u) | ✔️

**Review by wopian — CHANGES_REQUESTED** [review]
See above

**Comment by wopian** [comment]
~~Alternatively we could lowercase slugs on create/change, migrate existing slugs to lowercase and downcase search parameters?~~

Thoughts @NuckChorris?

**Comment by NuckChorris** [comment]
I think @wopian hit the nail on the head, that this won't work. In fact, my own slug is `Nuck`, so my profile wouldn't work with this.

Interestingly, we [already use the `citext` module for user slugs](https://github.com/hummingbird-me/kitsu-server/blob/db0da1ec37195cb441c6d74aceaefedfcb2f28d7/db/schema.rb#L1596), so this should already work. It's weird that it doesn't!

**Comment by wopian** [comment]
> Interestingly, we [already use the `citext` module for user slugs](https://github.com/hummingbird-me/kitsu-server/blob/db0da1ec37195cb441c6d74aceaefedfcb2f28d7/db/schema.rb#L1596), so this should already work. It's weird that it doesn't!

That's really odd.

Edit: Actually kinda makes sense for the error @toyhammered - it's getting `wopian` back (my slug) but trying to case-sensitive match somewhere (on GraphQL side).

```json
"error": {
  "message": "key not found: \"wopian\"\nDid you mean?  \"Wopian\""
}
```

```gql
query {
  findProfileBySlug(slug: "Wopian") {
    name
  }
}
```

Edit 2: Slugs with capitals only get `"message": "key not found: \"Nuck\""` when `findProfileBySlug(slug: "nuck")`

Edit 3: GraphQL(-Ruby)'s `String` type might not be aware of `CITEXT`?

**Comment by wopian** [comment]
@toyhammered, for specifically users, should `findProfileBySlug` also do an ID lookup if the input is all numbers? (All-number slugs are not allowed, so it _will_ be an ID)  

Since for most mobile users, their ID is their slug as far as the mobile and web clients are concerned.

I feel if it's left to API consumers to correctly perform either of the two options (slug for slugs and Id for Ids), users without slugs will unintentionally be left out of the developers' apps...I've already made this mistake once in another repo that supports multiple services, where I naively assumed it already did this 🙄

**Comment by toyhammered** [comment]
Thanks for all the research and testing @wopian! I'll see what is causing this error.

**Comment by NuckChorris** [comment]
Yknow what, it's the data loader. The batch code uses the key you pass to find the corresponding returned record in a hash. It'll need to be adjusted to allow for the case insensitive matching

**Comment by NuckChorris** [comment]
I just opened #929 with a full solution so I'm closing this one!

**Pull request closed without merging**
