### PR TITLE
GraphQL - search by user slug

### PR DESCRIPTION
**Pull request by toyhammered**
# What
Integrate with Algolia to allow search by user slug.

# Why

# Checklist

- [ ] All files pass Rubocop
- [ ] Any complex logic is commented
- [ ] Any new systems have thorough documentation
- [ ] Any user-facing changes are behind a feature flag (or: explain why they can't be)

- [ ] All the tests pass
- [ ] Tests have been added to cover the new code

### CODE REVIEW

**Comment by wopian** [comment]
The slight problem with this is mobile users and new web users won't be searchable as they don't have a slug. Of course, search by display name could be added in addition.

**Comment by wopian** [comment]
The slight problem with this is mobile users and new web users won't be searchable as they don't have a slug (the choice to not show slug during on boarding absolutely sucks - I'll see if its OK to add it for web users, mobile would have to wait for @NuckChorris' migration work to Expo). Of course, search by display name could be added in addition.

**Comment by NuckChorris** [comment]
Yeah this search should use display name.  IMO we should continue not requiring a slug, it's a silly legacy thing for the most part.

**Comment by wopian** [comment]
> Yeah this search should use display name. IMO we should continue not requiring a slug, it's a silly legacy thing for the most part.

But mentioning people without a slug is impossible (who knows someone else's ID???)

**Comment by toyhammered** [comment]
> > Yeah this search should use display name. IMO we should continue not requiring a slug, it's a silly legacy thing for the most part.
> 
> But mentioning people without a slug is impossible (who knows someone else's ID???)

#4195

**Review by NuckChorris — CHANGES_REQUESTED** [review]
This is weirdly specific, we pretty much never need to search by slug, you probably want to search by username instead

**Comment by toyhammered** [comment]
> This is weirdly specific, we pretty much never need to search by slug, you probably want to search by username instead

Updated to search by username (prioritize name, then slug)

**Review by NuckChorris — APPROVED** [review]

**Pull request merged**
