### PR TITLE
Nest episodes in anime admin page

### PR DESCRIPTION
**Pull request by matthewdias**
are nested attributes okay?

### CODE REVIEW

**Comment by NuckChorris** [comment]
I don't think we need `accepts_nested_attributes_for`, do we?  I thought rails_admin handled all that stuff via AJAX

**Comment by matthewdias** [comment]
this is apparently the only way to get an interface that allows deleting episodes from the media page.

**Comment by NuckChorris** [comment]
How well does it scale to like, 1000 episodes?

Does it crash?

**Comment by matthewdias** [comment]
doesn't crash, but it takes forever to generate all the html, and we get the gateway timeout, so long shows are inaccessible basically. i think ill revert this, and just see if i can tweak it so that episodes are displayed in order, or with their number in the info pane.

**Pull request merged**
