### PR TITLE
Remove synopsis validation in episode model again

### PR DESCRIPTION
**Pull request by kazzarin**
Deja vu? #97

### CODE REVIEW

**Comment by NuckChorris** [comment]
Dafuq how did that get back in there

**Comment by kazzarin** [comment]
Maybe from a merge conflict :thinking:

**Comment by NuckChorris** [comment]
Git blame says:

```
44ce234ac (Matthew Dias 2017-04-16 02:07:41 -0500 39)   validates :synopsis, length: { in: 50..600 }, allow_blank: true
```

👌

**Comment by matthewdias** [comment]
😅

**Pull request merged**
