### PR TITLE
Fix remaining bugs with Library Search

### PR DESCRIPTION
**Pull request by trmcnvn**
:memo:  See commit messages.

Confirmed working :+1:

Closes #130

### CODE REVIEW

**Comment by trmcnvn** [comment]
Timeout is still an issue, also a new ES error:

`"reason":"No mapping found for [status] in order to sort on"`

**Comment by NuckChorris** [comment]
I dunno if that's easily fixable, but I'll take a look. Dunno why it keeps giving timeouts, that's bizarre

**Comment by trmcnvn** [comment]
Scratch that, the other error isn't a timeout but:

```
"exception": "undefined method `id' for nil:NilClass",
"backtrace": [
"/app/vendor/bundle/ruby/2.3.0/gems/jsonapi-resources-0.9.0/lib/jsonapi/resource_serializer.rb:60:in `block in serialize_to_hash'",
```

**Comment by NuckChorris** [comment]
Wat. Is it giving a nil in the results? :thinking:

**Pull request merged**
